### ISSUE TITLE
Including Specific Humidity (QBOT)

### ISSUE THREAD

**Issue by hhollandmoritz** [NEONScience/NCAR-NEON#18]
Looks like one of the things the model needs to run is specific humidity at the base of the tower (QBOT). Right now we have relative humidity (RH). Is specific humidity at the base of the tower included in any NEON data product, or should we calculate it using a formula like this one: https://www.engineeringtoolbox.com/specific-relative-humidity-air-d_688.html

I'm happy to implement the formula, but if NEON already prepares this as a data product, I'd prefer to use the product.

**Comment by wwieder** [comment]
@hhollandmoritz we can just  use RH  for this one.  The model can calculate specific humidity on its own.  I think relative humidity is already being written out to the input files from the script.

**Comment by hhollandmoritz** [comment]
Yep, it is! Great. I didn't realize that either will work.

--
Hannah Holland-Moritz
Doctoral Candidate, Fierer Lab
EBIO Department
University of Colorado Boulder
she/her pronouns
hhollandmoritz@gmail.com
https://hhollandmoritz.github.io

**Comment by wwieder** [comment]
keep using RH as currently implimented
