### ISSUE TITLE
Gap filling data

### ISSUE THREAD

**Issue by wwieder** [NEONScience/NCAR-NEON#2]
I shared code using REddyProc for gapfilling, but will NEON be using or developing other tools to gap fill tower data (eg. eddy4R?

**Comment by ddurden** [comment]
The NEON data are sent to Ameriflux for gap-filling and higher level processing, such as u* filtering and partitioning. We have discussed the idea of collaborating with Ameriflux to run ONEFLUX at NEON, but nothing in the near term.
