### ISSUE TITLE
time stamps

### ISSUE THREAD

**Issue by wwieder** [NEONScience/NCAR-NEON#21]
I'm having troubles with the time stamps that are being written out for the .nc forcings in clm, which makes me wonder how we get data into UTC? 

Specifically, time units start at 7:00, not 0:00:00:

`double time(time) ;
		time:units = "days since 2018-01-01 07:00:00" ;`

@ddurden or @hhollandmoritz can you help clarify where to change this in the code?

**Comment by hhollandmoritz** [comment]
Could it be on line 149-150?

```
# Regularize timeseries to 30 minutes in case missing data after CI processing
timeRglr <- eddy4R.base::def.rglr(timeMeas = as.POSIXlt(dataDfFlux$TIMESTAMP_START), dataMeas = dataDfFlux, BgnRglr = as.POSIXlt(dataDfFlux$TIMESTAMP_START[1]), EndRglr = as.POSIXlt(dataDfFlux$TIMESTAMP_END[length(dataDfFlux$TIMESTAMP_END)]), TzRglr = "UTC", FreqRglr = 1/(60*30))
```
The as.POSIXlt statements default to the local timezone if no timezone is specified. All the other posix statements I searched for had timezones specified. I'm not exactly sure if the eddy4R.base would fix that or not.

From my interpretation, this would send GMT midnight start and end times to be converted which would then result in 7:00 UTC timestamps.

**Comment by wwieder** [comment]
So I need something like this?

timeRglr <- eddy4R.base::def.rglr(timeMeas =
as.POSIXlt(dataDfFlux$TIMESTAMP_START, tz = "UTC"),
                                  dataMeas = dataDfFlux,
                                  BgnRglr =
as.POSIXlt(dataDfFlux$TIMESTAMP_START[1], tz = "UTC"),
                                  EndRglr =
as.POSIXlt(dataDfFlux$TIMESTAMP_END[length(dataDfFlux$TIMESTAMP_END)], tz =
"UTC"),
                                  TzRglr = "UTC", FreqRglr = 1/(60*30))

**Comment by hhollandmoritz** [comment]
It's worth a try, just looking through the code, that's my suspicion. I don't recall messing with any of the times or dates in this code, so I'm not sure that it will work, but I had to do similar things with the Tvan and Ameriflux data for the NWT_CLM scripts.

**Comment by hhollandmoritz** [comment]
It's probably worth checking the timezone on the timestamps of `dataDfMet` around line 220, right before the flux and met data are combined together. 

Another place to look, if this doesn't work, is line 295 where the EddyProc.C location info is filled. It's a bit of a stretch because I'm pretty sure that EddyProcR doesn't actually change the timezones in any of its calculations.

**Comment by wwieder** [comment]
I changed these lines using `strftime`  make things work

`#Year month combination for data filtering`
`dataClm$yearMon <- strftime(dataClm$DateTime, "%Y-%m", tz='UTC')`

and below

`#Set of year/month combinations for netCDF output`
`setYearMon <- unique(strftime(dataClm$DateTime, "%Y-%m", tz='UTC'))`

Will push in a bit, but there are larger issues with NIWO data, @ddurden... not sure how best to proceed with large gaps in the data (starting Dec 2018) and obviously odd measurements in 2019.  Will start a new issue on this
