### ISSUE TITLE
missing and bad data

### ISSUE THREAD

**Issue by wwieder** [NEONScience/NCAR-NEON#23]
How should we handle missing or bad data?

Specifically NIWO has big data gaps that can't be filled (relative humidity missing for Dec 2018 - June 2019).

**OR**

Odd spikes in temperature and pressure in Jan & Feb 2019
<img width="620" alt="Screen Shot 2020-09-24 at 6 10 08 AM" src="https://user-images.githubusercontent.com/8031012/94143751-7ea5cd00-fe2d-11ea-8211-57742ede0377.png">

**Comment by wwieder** [comment]
@ddurden I noticed the comment about RH here.
https://github.com/NEONScience/NCAR-NEON/blob/8e37bc3ad1d56a13dc5e145a5c9e47886c00bb85/TowerTools_ForcingData/flow.api.clm.R#L298

Is there another data product for relative humidity we could be using?

**Comment by wwieder** [comment]
There also must be other temperature data we can use.  Big gaps, here from SCBI, as well as a few absurdly low values
![image](https://user-images.githubusercontent.com/8031012/94165921-f84ab480-fe47-11ea-9bad-b19842d67829.png)

**Comment by wwieder** [comment]
@ddurden said the new NEON data processing pipeline will improve the quality of flags that we can use for this.  What's the timeline for this release, Dave?

**Comment by ddurden** [comment]
@wwieder , we just finished reprocessing all the NEON data. Additionally, I just pulled in a robust regression gap-filling algorithm that will fill data from replicate, adjacent, or similar streams.

**Comment by wwieder** [comment]
awesome, @ddurden is this ready to go now, or are you still working on the script?

**Comment by ddurden** [comment]
@wwieder , the new data are available and just added the regression gap-filling function. I'm working on applying this to all driver data streams. I'm still targeting Jan. for data files being in ECS. However, if you want access to the updated function ahead of time I can point you to it.

**Comment by wwieder** [comment]
I think this issue is outdated,  with updates noted in #50
