### ISSUE TITLE
TBOT for OSBS in year 2018 is unrealistic 

### ISSUE THREAD

**Issue by jedwards4b** [NEONScience/NCAR-NEON#34]
in files atm/cdeps/v1/OSBS/2018-01.nc thru 2018-12.nc

// global attributes:
		:created_on = "Sat May  8 05:28:13 2021" ;
		:created_by = "David Durden" ;
		:created_from = "~/eddy/data/CLMv20210506/OSBS/OSBS_2018-01-01_2019-01-01.txt" ;
		:NEON\ site = "OSBS" ;
		:created_with = "flow.api.clm.R" ;
data:

 TBOT =
  562.124839257363,

**Comment by ddurden** [comment]
@jedwards4b , this is very strange I don't see any values over ~315 K. Can you tell me at what time this values occurred? I checked a couple of files directly and couldn't find any issues.
![image](https://user-images.githubusercontent.com/8151457/118589810-25e5c480-b76f-11eb-9abe-b130455c1aa1.png)

**Comment by wwieder** [comment]
looks like all data for Jan 2018 at OSBS are > 500K in the .nc file we have
/glade/scratch/dll/inputdata/atm/cdeps/v1/OSBS/2018-01.nc
Did we somehow grab  an old version of this file?  
![image](https://user-images.githubusercontent.com/8031012/118644603-357b0280-b79b-11eb-830b-2d957aa53880.png)

**Comment by wwieder** [comment]
same is true for data that we pulled down /glade/p/cesmdata/cseg/inputdata/atm/cdeps/v1/OSBS/2018-01.nc

**Comment by ddurden** [comment]
Here is the file I just pulled from S3, there must have been some modification during the download: 
![image](https://user-images.githubusercontent.com/8151457/118685461-1ac38080-b7d1-11eb-9388-7f5c71a3fcb9.png)

**Comment by ddurden** [comment]
looks like you may have tried to convert it from C to K.

**Comment by wwieder** [comment]
Wild, my plot was of the raw data we have on disk.  This must be related to #39 .  @negin513, maybe you can get rid of the OSBS data we have and re-download to cheyenne.

**Comment by ddurden** [comment]
I've reprocessed OSBS and BART with updates discussed. The new data should be available for download from these 2 sites.

**Comment by wwieder** [comment]
Thanks @ddurden, OSBS seems to run fine now
