### ISSUE TITLE
Post plots of NEON tower input data in S3 bucket

### ISSUE THREAD

**Issue by wwieder** [NEONScience/NCAR-NEON#36]
Moving the email thread here, but hopefully this can help us identify issues like #34 & #38
 
@ddurden  said: Data from 1/1/2018-12/31/2020 should be processed for NIWO, HARV, SCBI, OSBS, and KONZ. I’m producing some diagnostic plots if you feel they would be helpful. I’ve attached examples from HARV attached.

@wwieder responded: These diagnostics are really useful on our end for quickly diagnosing errors that may be causing issues in the model.  How / where should we share these data?

@ddurden: I guess we could store them in S3 bucket, but should we create a new folder or put it somewhere in the existing folder structure (eval_files folder)?

@wwieder: That would work. I like the idea of having another (input_data_eval) folder. The challenge on our end is knowing what data are available.  I wonder if there is an easier way that we can see what data are available in the S3 bucket?  Gordon will likely bring this up in our CICOE meeting next week.

@ddlenz Dave, we could do something similar to what we set up for access to your SAE data updates, e.g. a link to a bucket listing.
[HARV_forcing.pdf](https://github.com/NEONScience/NCAR-NEON/files/6481502/HARV_forcing.pdf)

**Comment by ddlenz** [comment]
Here's a link to a bucket listing: https://neon-ncar.s3.data.neonscience.org/listing.txt
Can be modified for content/format as needed..

**Comment by ddurden** [comment]
@wwieder , I'll work to add the diagnostic plots to the S3 bucket tomorrow. They should be picked up in the next run of the bucket listing workflow.

**Comment by ddlenz** [comment]
bucket listing changed to csv https://neon-ncar.s3.data.neonscience.org/listing.csv

**Comment by ddurden** [comment]
<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:/Users/ddurden/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///C:/Users/ddurden/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>





https://neon-ncar.s3.data.neonscience.org/NEON/atm/cdeps/v1/BART/BART_forcing.pdf | 5/18/2021 21:38
-- | --
https://neon-ncar.s3.data.neonscience.org/NEON/atm/cdeps/v1/BART/BART_gf_regressions.pdf | 5/18/2021 21:38
https://neon-ncar.s3.data.neonscience.org/NEON/atm/cdeps/v1/BART/BART_gf_variables.pdf | 5/18/2021 21:38
https://neon-ncar.s3.data.neonscience.org/NEON/atm/cdeps/v1/BART/BART_missing.pdf | 5/18/2021 21:38






Diagnostic plots now being written to S3, example listing from BART in the table above.

**Comment by wwieder** [comment]
This looks great. Are these data we want to bring over with file transfers from NEON to NCAR, @jedwards or @negin513?  If so, is this directory structure OK (e.g. pdf files in with the atm data for each site?)
