### ISSUE TITLE
Visualize data available in S3 bucket

### ISSUE THREAD

**Issue by wwieder** [NEONScience/NCAR-NEON#37]
There are a number of uses where it would be for helpful for NCAR to be able to actually see what's in the S3 bucket.  Is there a way to make this happen on the NEON end easily?  @ddlenz seems to think so, see #36

**Comment by ddlenz** [comment]
Here's a link to a bucket listing: https://neon-ncar.s3.data.neonscience.org/listing.txt
Can be modified for content/format as needed..

**Comment by ddurden** [comment]
Linked to #36

**Comment by wwieder** [comment]
If this list was enhanced with more metadata (including date created/updated) it may also address #39?
@negin513 and @jedwards

**Comment by ddlenz** [comment]
@ddurden @jedwards @negin513 @wwieder https://neon-ncar.s3.data.neonscience.org/listing.csv now includes last_modified

**Comment by wwieder** [comment]
Thanks @ddlenz. I'm going to leave this issue open until @jedwards confirms the listing is enough for use to also resolve #39.

**Comment by ddurden** [comment]
@jedwards can we close this issue?
