### ISSUE TITLE
rename NEON files for CLM 

### ISSUE THREAD

**Issue by wwieder** [NEONScience/NCAR-NEON#45]
To avoid confusion we've asked NEON to change the naming conventions for how files are named.
Paths will be identical as before but now will include site names and either `atm` or `eval`. For example
- `HARV_atm_2018-01.nc` & 
- `HARV_eval_2018-01.nc` 

@jedwards4b will you update this in the NEON compset so `datm_streams.xml` is populated correctly for each site?
@negin513, will you updated this in your visualization scripts?
@ddurden, will you update this on the NEON side and let us know when this is finished, also [in CTSM repo](https://github.com/ESCOMP/CTSM/issues/1442)

**Comment by wwieder** [comment]
@ddurden are the renamed files all up on the S3 bucket?  (for both _atm_ and _eval_ data)?

**Comment by jedwards4b** [comment]
Only JERC names have been changed at this time.

**Comment by ddurden** [comment]
@jedwards4b and @wwieder, the renamed files are all up now.

**Comment by wwieder** [comment]
Looks like this is resolved on the NEON side
