### ISSUE TITLE
Flexible code practices

### ISSUE THREAD

**Issue by wwieder** [NEONScience/NCAR-NEON#5]
Lots of hard coded aspects would be nice to integrate more flexibly with NEON data (e.g. site names, times of data coverage, location, etc). Not critical, but would help the code be more extensible for multple sites https://github.com/NEONScience/NCAR-NEON/blob/4e6c82d74b64b660542014665be70d96ac5122a3/TowerTools_ForcingData/Filled_makeNetCDF.R#L41

**Comment by ddurden** [comment]
This has been addressed by the latest updates to the code to grab metadata via the NEON HDF5 files.
